---
- hosts: jetson
  become: yes
  roles:
    - role: momo
      vars:
        momo_version: 2020.11
    - role: prometheus
      vars:
        prometheus_version: 2.22.0
    - role: node_exporter
      vars:
        node_exporter_version: 1.0.1
    - role: momo_exporter
      vars:
        momo_exporter_version: 0.1.0
