---
- name: create directory
  file:
    path: /opt/momo_exporter
    state: directory
    mode: 0755

- name: copy momo_exporter binary
  copy:
    src: momo_exporter
    dest: /opt/momo_exporter
    mode: 0755
  notify:
    - restart momo_exporter

- name: enabled and start momo_exporter service
  systemd:
    name: momo_exporter
    enabled: yes
    state: started
    daemon_reload: yes

- name: create link
  file:
    src: /opt/momo_exporter/momo_exporter
    dest: /usr/local/bin/momo_exporter
    state: link

- name: copy systemd file
  copy:
    src: momo_exporter.service
    dest: /etc/systemd/system/momo_exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart momo_exporter

- name: enabled and start momo_exporter service
  systemd:
    name: momo_exporter
    enabled: yes
    state: started
    daemon_reload: yes
